Vagrant.configure(2) do |config|
  config.vm.define "test.ezdeven.vagrant", primary: true, autostart: true do |config_machine|
      config.vm.synced_folder ".", "/vagrant", disabled: true
      #Assigning a provider
      config_machine.vm.provider :virtualbox do |virtualbox, override|
          virtualbox.name = "Test Vagrant eZDeven"
		  override.vm.box = "Test/eZDeven"
      end
  end
end
