Vagrant.configure(2) do |config|
  config.vm.define "test.phpstack.vagrant", primary: true, autostart: true do |config_machine|
    config.vm.synced_folder ".", "/vagrant", disabled: true
    #Assigning a provider
    config_machine.vm.provider :virtualbox do |virtualbox, override|
      virtualbox.name = "Test Vagrant PHPStack"
      override.vm.box = "Test/PHPStack"
      override.ssh.username = "ubuntu"
    end
  end
end
